[blur-my-shell]
appfolder-dialog-opacity=0.12
blur-dash=false
brightness=0.59999999999999998
dash-opacity=0.0
debug=false
hidetopbar=false
sigma=30

[coverflowalttab]
elastic-mode=false
icon-style='Overlay'
switcher-style='Coverflow'

[dash-to-dock]
apply-custom-theme=false
autohide-in-fullscreen=true
background-color='#000000'
background-opacity=0.0
custom-background-color=true
custom-theme-shrink=true
dash-max-icon-size=32
dock-fixed=false
dock-position='RIGHT'
extend-height=false
force-straight-corner=false
height-fraction=0.90000000000000002
icon-size-fixed=true
intellihide=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
isolate-monitors=true
isolate-workspaces=true
middle-click-action='launch'
multi-monitor=true
preferred-monitor=0
running-indicator-style='DOTS'
shift-click-action='minimize'
shift-middle-click-action='launch'
show-mounts=false
show-running=false
show-trash=false
transparency-mode='FIXED'

[hidetopbar]
enable-active-window=true
enable-intellihide=true
hot-corner=true
mouse-sensitive=true
mouse-sensitive-fullscreen-window=true
mouse-triggers-overview=false

[netspeedsimplified]
fontmode=0
isvertical=false
mode=3
restartextension=false
togglebool=false
wpos=0
wposext=1

[user-theme]
name='WhiteSur-dark'
