[dash-to-dock]
apply-custom-theme=false
autohide-in-fullscreen=true
background-opacity=0.0
custom-background-color=true
custom-theme-shrink=false
dash-max-icon-size=32
dock-fixed=false
dock-position='RIGHT'
extend-height=false
force-straight-corner=false
height-fraction=0.90000000000000002
icon-size-fixed=true
intellihide=true
intellihide-mode='FOCUS_APPLICATION_WINDOWS'
isolate-monitors=true
isolate-workspaces=true
multi-monitor=true
preferred-monitor=0
running-indicator-style='DEFAULT'
transparency-mode='FIXED'

[hidetopbar]
enable-active-window=true
enable-intellihide=true
hot-corner=true
mouse-sensitive=true
mouse-sensitive-fullscreen-window=true
mouse-triggers-overview=false

[simplenetspeed]
mode=3

[topicons-redux]
alignment='right'
offset=1

[topicons]
icon-brightness=2.7755575615628914e-17
icon-contrast=2.7755575615628914e-17
icon-opacity=200
icon-saturation=2.7755575615628914e-17
icon-size=16
icon-spacing=5
tray-pos='right'

[user-theme]
name='Mc-OS-CTLina-Gnome-Dark-1.3'

[workspaces-to-dock]
autohide-in-fullscreen=true
background-opacity=0.5
center-thumbnails-on-dock=true
center-thumbnails-option=0
customize-height=true
customize-height-option=0
customize-thumbnail=true
customize-thumbnail-visible-width=true
dock-fixed=false
dock-position='LEFT'
hide-dash=false
hide-workspace-switcher-popup=false
intellihide=true
intellihide-action='SHOW_FULL'
opaque-background=true
pressure-threshold=120.0
require-pressure-to-show=true
screen-edge-padding=0.0
scroll-with-touchpad=false
show-delay=0.25
straight-corners=false
thumbnail-visible-width=30.0
top-margin=0.0
workspace-captions=true
